export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS'
export const LINK_UPLOAD_FILE_SUCCESS = 'LINK_UPLOAD_FILE_SUCCESS'
export const GET_JOBS = 'GET_JOBS'
export const GET_REPORT_LIST = 'GET_REPORT_LIST'

