export default {
	DEFAULT_TOTAL_ITEM_PER_PAGE: 10,
	DEFAULT_PAGE_SIZES: [10, 20, 30, 50, 100],
	FULL_PAGE_SIZE: -1,
	DATE_FORMAT: {
		DDMMYYYY: 'DD/MM/YYYY',
		DDMMYYYYHHMMA: 'DD/MM/YYYY hh:mmA'
	},
	STATUS: ['inactive', 'active'],
}
